/* tslint:disable */
/* eslint-disable */
/**
 * ProjectHub
 * Jesus Antona Espejo
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonInput
 */
export interface PersonInput {
    /**
     * 
     * @type {string}
     * @memberof PersonInput
     */
    idPerson: string;
    /**
     * 
     * @type {string}
     * @memberof PersonInput
     */
    dNI: string;
    /**
     * 
     * @type {string}
     * @memberof PersonInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PersonInput
     */
    email: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonInput
     */
    pppoInternal?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonInput
     */
    pppoExternal?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PersonInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof PersonInput
     */
    company: string;
}

/**
 * Check if a given object implements the PersonInput interface.
 */
export function instanceOfPersonInput(value: object): boolean {
    if (!('idPerson' in value)) return false;
    if (!('dNI' in value)) return false;
    if (!('name' in value)) return false;
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    if (!('company' in value)) return false;
    return true;
}

export function PersonInputFromJSON(json: any): PersonInput {
    return PersonInputFromJSONTyped(json, false);
}

export function PersonInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonInput {
    if (json == null) {
        return json;
    }
    return {
        
        'idPerson': json['idPerson'],
        'dNI': json['DNI'],
        'name': json['name'],
        'email': json['email'],
        'pppoInternal': json['pppo_internal'] == null ? undefined : json['pppo_internal'],
        'pppoExternal': json['pppo_external'] == null ? undefined : json['pppo_external'],
        'password': json['password'],
        'company': json['company'],
    };
}

export function PersonInputToJSON(value?: PersonInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idPerson': value['idPerson'],
        'DNI': value['dNI'],
        'name': value['name'],
        'email': value['email'],
        'pppo_internal': value['pppoInternal'],
        'pppo_external': value['pppoExternal'],
        'password': value['password'],
        'company': value['company'],
    };
}

