/* tslint:disable */
/* eslint-disable */
/**
 * ProjectHub
 * Jesus Antona Espejo
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PPPOOutput
 */
export interface PPPOOutput {
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    idPPPO: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    company: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    parentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    plannedValue: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    actualCost: number;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    finishDate: string | null;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    startRealDate: string | null;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    finishRealDate: string | null;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    risk: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    priority: number;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    strategicGoal: string;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    earnedValue: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    rOI: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    costBenefit: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOOutput
     */
    pPPO: number;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    internalManager: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOOutput
     */
    externalManager: string | null;
}

/**
 * Check if a given object implements the PPPOOutput interface.
 */
export function instanceOfPPPOOutput(value: object): boolean {
    if (!('idPPPO' in value)) return false;
    if (!('code' in value)) return false;
    if (!('company' in value)) return false;
    if (!('parentId' in value)) return false;
    if (!('title' in value)) return false;
    if (!('description' in value)) return false;
    if (!('plannedValue' in value)) return false;
    if (!('actualCost' in value)) return false;
    if (!('startDate' in value)) return false;
    if (!('finishDate' in value)) return false;
    if (!('startRealDate' in value)) return false;
    if (!('finishRealDate' in value)) return false;
    if (!('risk' in value)) return false;
    if (!('priority' in value)) return false;
    if (!('strategicGoal' in value)) return false;
    if (!('earnedValue' in value)) return false;
    if (!('rOI' in value)) return false;
    if (!('costBenefit' in value)) return false;
    if (!('pPPO' in value)) return false;
    if (!('state' in value)) return false;
    if (!('internalManager' in value)) return false;
    if (!('externalManager' in value)) return false;
    return true;
}

export function PPPOOutputFromJSON(json: any): PPPOOutput {
    return PPPOOutputFromJSONTyped(json, false);
}

export function PPPOOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PPPOOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'idPPPO': json['idPPPO'],
        'code': json['code'],
        'company': json['company'],
        'parentId': json['parent_id'],
        'title': json['title'],
        'description': json['description'],
        'plannedValue': json['planned_value'],
        'actualCost': json['actual_cost'],
        'startDate': json['start_date'],
        'finishDate': json['finish_date'],
        'startRealDate': json['start_real_date'],
        'finishRealDate': json['finish_real_date'],
        'risk': json['risk'],
        'priority': json['priority'],
        'strategicGoal': json['strategic_goal'],
        'earnedValue': json['earned_value'],
        'rOI': json['ROI'],
        'costBenefit': json['cost_benefit'],
        'pPPO': json['PPPO'],
        'state': json['state'],
        'internalManager': json['internal_manager'],
        'externalManager': json['external_manager'],
    };
}

export function PPPOOutputToJSON(value?: PPPOOutput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idPPPO': value['idPPPO'],
        'code': value['code'],
        'company': value['company'],
        'parent_id': value['parentId'],
        'title': value['title'],
        'description': value['description'],
        'planned_value': value['plannedValue'],
        'actual_cost': value['actualCost'],
        'start_date': value['startDate'],
        'finish_date': value['finishDate'],
        'start_real_date': value['startRealDate'],
        'finish_real_date': value['finishRealDate'],
        'risk': value['risk'],
        'priority': value['priority'],
        'strategic_goal': value['strategicGoal'],
        'earned_value': value['earnedValue'],
        'ROI': value['rOI'],
        'cost_benefit': value['costBenefit'],
        'PPPO': value['pPPO'],
        'state': value['state'],
        'internal_manager': value['internalManager'],
        'external_manager': value['externalManager'],
    };
}

