/* tslint:disable */
/* eslint-disable */
/**
 * ProjectHub
 * Jesus Antona Espejo
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    idCompany: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    nIF: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    name: string;
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): boolean {
    if (!('idCompany' in value)) return false;
    if (!('code' in value)) return false;
    if (!('nIF' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if (json == null) {
        return json;
    }
    return {
        
        'idCompany': json['idCompany'],
        'code': json['code'],
        'nIF': json['NIF'],
        'name': json['name'],
    };
}

export function CompanyToJSON(value?: Company | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idCompany': value['idCompany'],
        'code': value['code'],
        'NIF': value['nIF'],
        'name': value['name'],
    };
}

