/* tslint:disable */
/* eslint-disable */
/**
 * ProjectHub
 * Jesus Antona Espejo
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PPPOInput
 */
export interface PPPOInput {
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    idPPPO: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    company: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    plannedValue: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    actualCost: number;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    finishDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    startRealDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    finishRealDate?: string;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    risk: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    priority: number;
    /**
     * 
     * @type {string}
     * @memberof PPPOInput
     */
    strategicGoal: string;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    earnedValue: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    rOI: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    costBenefit: number;
    /**
     * 
     * @type {number}
     * @memberof PPPOInput
     */
    pPPO: number;
}

/**
 * Check if a given object implements the PPPOInput interface.
 */
export function instanceOfPPPOInput(value: object): boolean {
    if (!('idPPPO' in value)) return false;
    if (!('code' in value)) return false;
    if (!('company' in value)) return false;
    if (!('title' in value)) return false;
    if (!('description' in value)) return false;
    if (!('plannedValue' in value)) return false;
    if (!('actualCost' in value)) return false;
    if (!('startDate' in value)) return false;
    if (!('risk' in value)) return false;
    if (!('priority' in value)) return false;
    if (!('strategicGoal' in value)) return false;
    if (!('earnedValue' in value)) return false;
    if (!('rOI' in value)) return false;
    if (!('costBenefit' in value)) return false;
    if (!('pPPO' in value)) return false;
    return true;
}

export function PPPOInputFromJSON(json: any): PPPOInput {
    return PPPOInputFromJSONTyped(json, false);
}

export function PPPOInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PPPOInput {
    if (json == null) {
        return json;
    }
    return {
        
        'idPPPO': json['idPPPO'],
        'code': json['code'],
        'company': json['company'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'title': json['title'],
        'description': json['description'],
        'plannedValue': json['planned_value'],
        'actualCost': json['actual_cost'],
        'startDate': json['start_date'],
        'finishDate': json['finish_date'] == null ? undefined : json['finish_date'],
        'startRealDate': json['start_real_date'] == null ? undefined : json['start_real_date'],
        'finishRealDate': json['finish_real_date'] == null ? undefined : json['finish_real_date'],
        'risk': json['risk'],
        'priority': json['priority'],
        'strategicGoal': json['strategic_goal'],
        'earnedValue': json['earned_value'],
        'rOI': json['ROI'],
        'costBenefit': json['cost_benefit'],
        'pPPO': json['PPPO'],
    };
}

export function PPPOInputToJSON(value?: PPPOInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idPPPO': value['idPPPO'],
        'code': value['code'],
        'company': value['company'],
        'parent_id': value['parentId'],
        'title': value['title'],
        'description': value['description'],
        'planned_value': value['plannedValue'],
        'actual_cost': value['actualCost'],
        'start_date': value['startDate'],
        'finish_date': value['finishDate'],
        'start_real_date': value['startRealDate'],
        'finish_real_date': value['finishRealDate'],
        'risk': value['risk'],
        'priority': value['priority'],
        'strategic_goal': value['strategicGoal'],
        'earned_value': value['earnedValue'],
        'ROI': value['rOI'],
        'cost_benefit': value['costBenefit'],
        'PPPO': value['pPPO'],
    };
}

