/* tslint:disable */
/* eslint-disable */
/**
 * ProjectHub
 * Jesus Antona Espejo
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface State
 */
export interface State {
    /**
     * 
     * @type {string}
     * @memberof State
     */
    idState: string;
    /**
     * 
     * @type {string}
     * @memberof State
     */
    state: string;
    /**
     * 
     * @type {number}
     * @memberof State
     */
    type: number;
}

/**
 * Check if a given object implements the State interface.
 */
export function instanceOfState(value: object): boolean {
    if (!('idState' in value)) return false;
    if (!('state' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function StateFromJSON(json: any): State {
    return StateFromJSONTyped(json, false);
}

export function StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): State {
    if (json == null) {
        return json;
    }
    return {
        
        'idState': json['idState'],
        'state': json['state'],
        'type': json['type'],
    };
}

export function StateToJSON(value?: State | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idState': value['idState'],
        'state': value['state'],
        'type': value['type'],
    };
}

